<?php

namespace App\Services;

class MaritimeIdentityService
{
    /**
     * Get Country, Continent, Timezone, and ISO Country Code data from an MMSI number.
     * Extracts the 3-digit MID (Maritime Identification Digits) to identify the flag.
     */
    public static function getFlagData(int $mmsi): array
    {
        // Extract the first 3 digits (MID)
        $mid = (int) substr((string) $mmsi, 0, 3);

        $midMap = [
            // Europe
            201 => ['country' => 'Albania', 'code' => 'AL', 'continent' => 'Europe', 'tz' => 'Europe/Tirane'],
            202 => ['country' => 'Andorra', 'code' => 'AD', 'continent' => 'Europe', 'tz' => 'Europe/Andorra'],
            203 => ['country' => 'Austria', 'code' => 'AT', 'continent' => 'Europe', 'tz' => 'Europe/Vienna'],
            204 => ['country' => 'Azores', 'code' => 'PT', 'continent' => 'Europe', 'tz' => 'Atlantic/Azores'],
            205 => ['country' => 'Belgium', 'code' => 'BE', 'continent' => 'Europe', 'tz' => 'Europe/Brussels'],
            206 => ['country' => 'Belarus', 'code' => 'BY', 'continent' => 'Europe', 'tz' => 'Europe/Minsk'],
            207 => ['country' => 'Bulgaria', 'code' => 'BG', 'continent' => 'Europe', 'tz' => 'Europe/Sofia'],
            208 => ['country' => 'Vatican City', 'code' => 'VA', 'continent' => 'Europe', 'tz' => 'Europe/Vatican'],
            209 => ['country' => 'Cyprus', 'code' => 'CY', 'continent' => 'Europe', 'tz' => 'Asia/Nicosia'],
            210 => ['country' => 'Cyprus', 'code' => 'CY', 'continent' => 'Europe', 'tz' => 'Asia/Nicosia'],
            211 => ['country' => 'Germany', 'code' => 'DE', 'continent' => 'Europe', 'tz' => 'Europe/Berlin'],
            212 => ['country' => 'Cyprus', 'code' => 'CY', 'continent' => 'Europe', 'tz' => 'Asia/Nicosia'],
            213 => ['country' => 'Georgia', 'code' => 'GE', 'continent' => 'Europe', 'tz' => 'Asia/Tbilisi'],
            214 => ['country' => 'Moldova', 'code' => 'MD', 'continent' => 'Europe', 'tz' => 'Europe/Chisinau'],
            215 => ['country' => 'Malta', 'code' => 'MT', 'continent' => 'Europe', 'tz' => 'Europe/Malta'],
            216 => ['country' => 'Armenia', 'code' => 'AM', 'continent' => 'Europe', 'tz' => 'Asia/Yerevan'],
            218 => ['country' => 'Germany', 'code' => 'DE', 'continent' => 'Europe', 'tz' => 'Europe/Berlin'],
            219 => ['country' => 'Denmark', 'code' => 'DK', 'continent' => 'Europe', 'tz' => 'Europe/Copenhagen'],
            220 => ['country' => 'Denmark', 'code' => 'DK', 'continent' => 'Europe', 'tz' => 'Europe/Copenhagen'],
            224 => ['country' => 'Spain', 'code' => 'ES', 'continent' => 'Europe', 'tz' => 'Europe/Madrid'],
            225 => ['country' => 'Spain', 'code' => 'ES', 'continent' => 'Europe', 'tz' => 'Europe/Madrid'],
            226 => ['country' => 'France', 'code' => 'FR', 'continent' => 'Europe', 'tz' => 'Europe/Paris'],
            227 => ['country' => 'France', 'code' => 'FR', 'continent' => 'Europe', 'tz' => 'Europe/Paris'],
            228 => ['country' => 'France', 'code' => 'FR', 'continent' => 'Europe', 'tz' => 'Europe/Paris'],
            229 => ['country' => 'Malta', 'code' => 'MT', 'continent' => 'Europe', 'tz' => 'Europe/Malta'],
            230 => ['country' => 'Finland', 'code' => 'FI', 'continent' => 'Europe', 'tz' => 'Europe/Helsinki'],
            231 => ['country' => 'Faroe Islands', 'code' => 'FO', 'continent' => 'Europe', 'tz' => 'Atlantic/Faroe'],
            232 => ['country' => 'United Kingdom', 'code' => 'GB', 'continent' => 'Europe', 'tz' => 'Europe/London'],
            233 => ['country' => 'United Kingdom', 'code' => 'GB', 'continent' => 'Europe', 'tz' => 'Europe/London'],
            234 => ['country' => 'United Kingdom', 'code' => 'GB', 'continent' => 'Europe', 'tz' => 'Europe/London'],
            235 => ['country' => 'United Kingdom', 'code' => 'GB', 'continent' => 'Europe', 'tz' => 'Europe/London'],
            236 => ['country' => 'Gibraltar', 'code' => 'GI', 'continent' => 'Europe', 'tz' => 'Europe/Gibraltar'],
            237 => ['country' => 'Greece', 'code' => 'GR', 'continent' => 'Europe', 'tz' => 'Europe/Athens'],
            238 => ['country' => 'Croatia', 'code' => 'HR', 'continent' => 'Europe', 'tz' => 'Europe/Zagreb'],
            239 => ['country' => 'Greece', 'code' => 'GR', 'continent' => 'Europe', 'tz' => 'Europe/Athens'],
            240 => ['country' => 'Greece', 'code' => 'GR', 'continent' => 'Europe', 'tz' => 'Europe/Athens'],
            241 => ['country' => 'Greece', 'code' => 'GR', 'continent' => 'Europe', 'tz' => 'Europe/Athens'],
            242 => ['country' => 'Morocco', 'code' => 'MA', 'continent' => 'Africa', 'tz' => 'Africa/Casablanca'],
            243 => ['country' => 'Hungary', 'code' => 'HU', 'continent' => 'Europe', 'tz' => 'Europe/Budapest'],
            244 => ['country' => 'Netherlands', 'code' => 'NL', 'continent' => 'Europe', 'tz' => 'Europe/Amsterdam'],
            245 => ['country' => 'Netherlands', 'code' => 'NL', 'continent' => 'Europe', 'tz' => 'Europe/Amsterdam'],
            246 => ['country' => 'Netherlands', 'code' => 'NL', 'continent' => 'Europe', 'tz' => 'Europe/Amsterdam'],
            247 => ['country' => 'Italy', 'code' => 'IT', 'continent' => 'Europe', 'tz' => 'Europe/Rome'],
            248 => ['country' => 'Malta', 'code' => 'MT', 'continent' => 'Europe', 'tz' => 'Europe/Malta'],
            249 => ['country' => 'Malta', 'code' => 'MT', 'continent' => 'Europe', 'tz' => 'Europe/Malta'],
            250 => ['country' => 'Ireland', 'code' => 'IE', 'continent' => 'Europe', 'tz' => 'Europe/Dublin'],
            251 => ['country' => 'Iceland', 'code' => 'IS', 'continent' => 'Europe', 'tz' => 'Atlantic/Reykjavik'],
            252 => ['country' => 'Liechtenstein', 'code' => 'LI', 'continent' => 'Europe', 'tz' => 'Europe/Vaduz'],
            253 => ['country' => 'Luxembourg', 'code' => 'LU', 'continent' => 'Europe', 'tz' => 'Europe/Luxembourg'],
            254 => ['country' => 'Monaco', 'code' => 'MC', 'continent' => 'Europe', 'tz' => 'Europe/Monaco'],
            255 => ['country' => 'Portugal (Madeira)', 'code' => 'PT', 'continent' => 'Europe', 'tz' => 'Atlantic/Madeira'],
            256 => ['country' => 'Malta', 'code' => 'MT', 'continent' => 'Europe', 'tz' => 'Europe/Malta'],
            257 => ['country' => 'Norway', 'code' => 'NO', 'continent' => 'Europe', 'tz' => 'Europe/Oslo'],
            258 => ['country' => 'Norway', 'code' => 'NO', 'continent' => 'Europe', 'tz' => 'Europe/Oslo'],
            259 => ['country' => 'Norway', 'code' => 'NO', 'continent' => 'Europe', 'tz' => 'Europe/Oslo'],
            261 => ['country' => 'Poland', 'code' => 'PL', 'continent' => 'Europe', 'tz' => 'Europe/Warsaw'],
            262 => ['country' => 'Montenegro', 'code' => 'ME', 'continent' => 'Europe', 'tz' => 'Europe/Podgorica'],
            263 => ['country' => 'Portugal', 'code' => 'PT', 'continent' => 'Europe', 'tz' => 'Europe/Lisbon'],
            264 => ['country' => 'Romania', 'code' => 'RO', 'continent' => 'Europe', 'tz' => 'Europe/Bucharest'],
            265 => ['country' => 'Sweden', 'code' => 'SE', 'continent' => 'Europe', 'tz' => 'Europe/Stockholm'],
            266 => ['country' => 'Sweden', 'code' => 'SE', 'continent' => 'Europe', 'tz' => 'Europe/Stockholm'],
            267 => ['country' => 'Slovakia', 'code' => 'SK', 'continent' => 'Europe', 'tz' => 'Europe/Bratislava'],
            268 => ['country' => 'San Marino', 'code' => 'SM', 'continent' => 'Europe', 'tz' => 'Europe/San_Marino'],
            269 => ['country' => 'Switzerland', 'code' => 'CH', 'continent' => 'Europe', 'tz' => 'Europe/Zurich'],
            270 => ['country' => 'Czech Republic', 'code' => 'CZ', 'continent' => 'Europe', 'tz' => 'Europe/Prague'],
            271 => ['country' => 'Turkey', 'code' => 'TR', 'continent' => 'Europe', 'tz' => 'Europe/Istanbul'],
            272 => ['country' => 'Ukraine', 'code' => 'UA', 'continent' => 'Europe', 'tz' => 'Europe/Kyiv'],
            273 => ['country' => 'Russia', 'code' => 'RU', 'continent' => 'Europe', 'tz' => 'Europe/Moscow'],
            274 => ['country' => 'North Macedonia', 'code' => 'MK', 'continent' => 'Europe', 'tz' => 'Europe/Skopje'],
            275 => ['country' => 'Latvia', 'code' => 'LV', 'continent' => 'Europe', 'tz' => 'Europe/Riga'],
            276 => ['country' => 'Estonia', 'code' => 'EE', 'continent' => 'Europe', 'tz' => 'Europe/Tallinn'],
            277 => ['country' => 'Lithuania', 'code' => 'LT', 'continent' => 'Europe', 'tz' => 'Europe/Vilnius'],
            278 => ['country' => 'Slovenia', 'code' => 'SI', 'continent' => 'Europe', 'tz' => 'Europe/Ljubljana'],
            279 => ['country' => 'Serbia', 'code' => 'RS', 'continent' => 'Europe', 'tz' => 'Europe/Belgrade'],

            // North & Central America
            301 => ['country' => 'Anguilla', 'code' => 'AI', 'continent' => 'North America', 'tz' => 'America/Anguilla'],
            303 => ['country' => 'Alaska', 'code' => 'US', 'continent' => 'North America', 'tz' => 'America/Anchorage'],
            304 => ['country' => 'Antigua and Barbuda', 'code' => 'AG', 'continent' => 'North America', 'tz' => 'America/Antigua'],
            305 => ['country' => 'Antigua and Barbuda', 'code' => 'AG', 'continent' => 'North America', 'tz' => 'America/Antigua'],
            306 => ['country' => 'Curaçao', 'code' => 'CW', 'continent' => 'North America', 'tz' => 'America/Curacao'],
            307 => ['country' => 'Aruba', 'code' => 'AW', 'continent' => 'North America', 'tz' => 'America/Aruba'],
            308 => ['country' => 'Bahamas', 'code' => 'BS', 'continent' => 'North America', 'tz' => 'America/Nassau'],
            309 => ['country' => 'Bahamas', 'code' => 'BS', 'continent' => 'North America', 'tz' => 'America/Nassau'],
            310 => ['country' => 'Bermuda', 'code' => 'BM', 'continent' => 'North America', 'tz' => 'Atlantic/Bermuda'],
            311 => ['country' => 'Bahamas', 'code' => 'BS', 'continent' => 'North America', 'tz' => 'America/Nassau'],
            312 => ['country' => 'Belize', 'code' => 'BZ', 'continent' => 'North America', 'tz' => 'America/Belize'],
            314 => ['country' => 'Barbados', 'code' => 'BB', 'continent' => 'North America', 'tz' => 'America/Barbados'],
            316 => ['country' => 'Canada', 'code' => 'CA', 'continent' => 'North America', 'tz' => 'America/Toronto'],
            319 => ['country' => 'Cayman Islands', 'code' => 'KY', 'continent' => 'North America', 'tz' => 'America/Cayman'],
            321 => ['country' => 'Costa Rica', 'code' => 'CR', 'continent' => 'North America', 'tz' => 'America/Costa_Rica'],
            323 => ['country' => 'Cuba', 'code' => 'CU', 'continent' => 'North America', 'tz' => 'America/Havana'],
            325 => ['country' => 'Dominica', 'code' => 'DM', 'continent' => 'North America', 'tz' => 'America/Dominica'],
            327 => ['country' => 'Dominican Republic', 'code' => 'DO', 'continent' => 'North America', 'tz' => 'America/Santo_Domingo'],
            329 => ['country' => 'Guadeloupe', 'code' => 'GP', 'continent' => 'North America', 'tz' => 'America/Guadeloupe'],
            330 => ['country' => 'Grenada', 'code' => 'GD', 'continent' => 'North America', 'tz' => 'America/Grenada'],
            331 => ['country' => 'Greenland', 'code' => 'GL', 'continent' => 'North America', 'tz' => 'America/Nuuk'],
            332 => ['country' => 'Guatemala', 'code' => 'GT', 'continent' => 'North America', 'tz' => 'America/Guatemala'],
            334 => ['country' => 'Honduras', 'code' => 'HN', 'continent' => 'North America', 'tz' => 'America/Tegucigalpa'],
            336 => ['country' => 'Haiti', 'code' => 'HT', 'continent' => 'North America', 'tz' => 'America/Port-au-Prince'],
            338 => ['country' => 'Jamaica', 'code' => 'JM', 'continent' => 'North America', 'tz' => 'America/Jamaica'],
            339 => ['country' => 'Jamaica', 'code' => 'JM', 'continent' => 'North America', 'tz' => 'America/Jamaica'],
            341 => ['country' => 'Saint Kitts and Nevis', 'code' => 'KN', 'continent' => 'North America', 'tz' => 'America/St_Kitts'],
            343 => ['country' => 'Saint Lucia', 'code' => 'LC', 'continent' => 'North America', 'tz' => 'America/St_Lucia'],
            345 => ['country' => 'Mexico', 'code' => 'MX', 'continent' => 'North America', 'tz' => 'America/Mexico_City'],
            347 => ['country' => 'Martinique', 'code' => 'MQ', 'continent' => 'North America', 'tz' => 'America/Martinique'],
            348 => ['country' => 'Montserrat', 'code' => 'MS', 'continent' => 'North America', 'tz' => 'America/Montserrat'],
            350 => ['country' => 'Nicaragua', 'code' => 'NI', 'continent' => 'North America', 'tz' => 'America/Managua'],
            351 => ['country' => 'Panama', 'code' => 'PA', 'continent' => 'North America', 'tz' => 'America/Panama'],
            352 => ['country' => 'Panama', 'code' => 'PA', 'continent' => 'North America', 'tz' => 'America/Panama'],
            353 => ['country' => 'Panama', 'code' => 'PA', 'continent' => 'North America', 'tz' => 'America/Panama'],
            354 => ['country' => 'Panama', 'code' => 'PA', 'continent' => 'North America', 'tz' => 'America/Panama'],
            355 => ['country' => 'Panama', 'code' => 'PA', 'continent' => 'North America', 'tz' => 'America/Panama'],
            356 => ['country' => 'Panama', 'code' => 'PA', 'continent' => 'North America', 'tz' => 'America/Panama'],
            357 => ['country' => 'Panama', 'code' => 'PA', 'continent' => 'North America', 'tz' => 'America/Panama'],
            358 => ['country' => 'Puerto Rico', 'code' => 'PR', 'continent' => 'North America', 'tz' => 'America/Puerto_Rico'],
            359 => ['country' => 'El Salvador', 'code' => 'SV', 'continent' => 'North America', 'tz' => 'America/El_Salvador'],
            361 => ['country' => 'Saint Pierre and Miquelon', 'code' => 'PM', 'continent' => 'North America', 'tz' => 'America/Miquelon'],
            362 => ['country' => 'Trinidad and Tobago', 'code' => 'TT', 'continent' => 'North America', 'tz' => 'America/Port_of_Spain'],
            364 => ['country' => 'Turks and Caicos Islands', 'code' => 'TC', 'continent' => 'North America', 'tz' => 'America/Grand_Turk'],
            366 => ['country' => 'United States', 'code' => 'US', 'continent' => 'North America', 'tz' => 'America/New_York'],
            367 => ['country' => 'United States', 'code' => 'US', 'continent' => 'North America', 'tz' => 'America/New_York'],
            368 => ['country' => 'United States', 'code' => 'US', 'continent' => 'North America', 'tz' => 'America/New_York'],
            369 => ['country' => 'United States', 'code' => 'US', 'continent' => 'North America', 'tz' => 'America/New_York'],
            370 => ['country' => 'Panama', 'code' => 'PA', 'continent' => 'North America', 'tz' => 'America/Panama'],
            371 => ['country' => 'Panama', 'code' => 'PA', 'continent' => 'North America', 'tz' => 'America/Panama'],
            372 => ['country' => 'Panama', 'code' => 'PA', 'continent' => 'North America', 'tz' => 'America/Panama'],
            373 => ['country' => 'Panama', 'code' => 'PA', 'continent' => 'North America', 'tz' => 'America/Panama'],
            374 => ['country' => 'Panama', 'code' => 'PA', 'continent' => 'North America', 'tz' => 'America/Panama'],
            375 => ['country' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'continent' => 'North America', 'tz' => 'America/St_Vincent'],
            376 => ['country' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'continent' => 'North America', 'tz' => 'America/St_Vincent'],
            377 => ['country' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'continent' => 'North America', 'tz' => 'America/St_Vincent'],
            378 => ['country' => 'British Virgin Islands', 'code' => 'VG', 'continent' => 'North America', 'tz' => 'America/Tortola'],
            379 => ['country' => 'US Virgin Islands', 'code' => 'VI', 'continent' => 'North America', 'tz' => 'America/St_Thomas'],

            // Asia
            401 => ['country' => 'Afghanistan', 'code' => 'AF', 'continent' => 'Asia', 'tz' => 'Asia/Kabul'],
            403 => ['country' => 'Saudi Arabia', 'code' => 'SA', 'continent' => 'Asia', 'tz' => 'Asia/Riyadh'],
            405 => ['country' => 'Bangladesh', 'code' => 'BD', 'continent' => 'Asia', 'tz' => 'Asia/Dhaka'],
            408 => ['country' => 'Bahrain', 'code' => 'BH', 'continent' => 'Asia', 'tz' => 'Asia/Bahrain'],
            410 => ['country' => 'Bhutan', 'code' => 'BT', 'continent' => 'Asia', 'tz' => 'Asia/Thimphu'],
            412 => ['country' => 'China', 'code' => 'CN', 'continent' => 'Asia', 'tz' => 'Asia/Shanghai'],
            413 => ['country' => 'China', 'code' => 'CN', 'continent' => 'Asia', 'tz' => 'Asia/Shanghai'],
            414 => ['country' => 'China', 'code' => 'CN', 'continent' => 'Asia', 'tz' => 'Asia/Shanghai'],
            416 => ['country' => 'Taiwan', 'code' => 'TW', 'continent' => 'Asia', 'tz' => 'Asia/Taipei'],
            417 => ['country' => 'Sri Lanka', 'code' => 'LK', 'continent' => 'Asia', 'tz' => 'Asia/Colombo'],
            419 => ['country' => 'India', 'code' => 'IN', 'continent' => 'Asia', 'tz' => 'Asia/Kolkata'],
            422 => ['country' => 'Iran', 'code' => 'IR', 'continent' => 'Asia', 'tz' => 'Asia/Tehran'],
            423 => ['country' => 'Azerbaijan', 'code' => 'AZ', 'continent' => 'Asia', 'tz' => 'Asia/Baku'],
            425 => ['country' => 'Iraq', 'code' => 'IQ', 'continent' => 'Asia', 'tz' => 'Asia/Baghdad'],
            428 => ['country' => 'Israel', 'code' => 'IL', 'continent' => 'Asia', 'tz' => 'Asia/Jerusalem'],
            431 => ['country' => 'Japan', 'code' => 'JP', 'continent' => 'Asia', 'tz' => 'Asia/Tokyo'],
            432 => ['country' => 'Japan', 'code' => 'JP', 'continent' => 'Asia', 'tz' => 'Asia/Tokyo'],
            434 => ['country' => 'Turkmenistan', 'code' => 'TM', 'continent' => 'Asia', 'tz' => 'Asia/Ashgabat'],
            436 => ['country' => 'Kazakhstan', 'code' => 'KZ', 'continent' => 'Asia', 'tz' => 'Asia/Almaty'],
            437 => ['country' => 'Uzbekistan', 'code' => 'UZ', 'continent' => 'Asia', 'tz' => 'Asia/Tashkent'],
            438 => ['country' => 'Jordan', 'code' => 'JO', 'continent' => 'Asia', 'tz' => 'Asia/Amman'],
            440 => ['country' => 'South Korea', 'code' => 'KR', 'continent' => 'Asia', 'tz' => 'Asia/Seoul'],
            441 => ['country' => 'South Korea', 'code' => 'KR', 'continent' => 'Asia', 'tz' => 'Asia/Seoul'],
            443 => ['country' => 'Palestine', 'code' => 'PS', 'continent' => 'Asia', 'tz' => 'Asia/Gaza'],
            445 => ['country' => 'North Korea', 'code' => 'KP', 'continent' => 'Asia', 'tz' => 'Asia/Pyongyang'],
            447 => ['country' => 'Kuwait', 'code' => 'KW', 'continent' => 'Asia', 'tz' => 'Asia/Kuwait'],
            450 => ['country' => 'Lebanon', 'code' => 'LB', 'continent' => 'Asia', 'tz' => 'Asia/Beirut'],
            451 => ['country' => 'Kyrgyzstan', 'code' => 'KG', 'continent' => 'Asia', 'tz' => 'Asia/Bishkek'],
            453 => ['country' => 'Macau', 'code' => 'MO', 'continent' => 'Asia', 'tz' => 'Asia/Macau'],
            455 => ['country' => 'Maldives', 'code' => 'MV', 'continent' => 'Asia', 'tz' => 'Indian/Maldives'],
            457 => ['country' => 'Mongolia', 'code' => 'MN', 'continent' => 'Asia', 'tz' => 'Asia/Ulaanbaatar'],
            459 => ['country' => 'Nepal', 'code' => 'NP', 'continent' => 'Asia', 'tz' => 'Asia/Kathmandu'],
            461 => ['country' => 'Oman', 'code' => 'OM', 'continent' => 'Asia', 'tz' => 'Asia/Muscat'],
            463 => ['country' => 'Pakistan', 'code' => 'PK', 'continent' => 'Asia', 'tz' => 'Asia/Karachi'],
            466 => ['country' => 'Qatar', 'code' => 'QA', 'continent' => 'Asia', 'tz' => 'Asia/Qatar'],
            468 => ['country' => 'Syria', 'code' => 'SY', 'continent' => 'Asia', 'tz' => 'Asia/Damascus'],
            470 => ['country' => 'United Arab Emirates', 'code' => 'AE', 'continent' => 'Asia', 'tz' => 'Asia/Dubai'],
            471 => ['country' => 'United Arab Emirates', 'code' => 'AE', 'continent' => 'Asia', 'tz' => 'Asia/Dubai'],
            472 => ['country' => 'Tajikistan', 'code' => 'TJ', 'continent' => 'Asia', 'tz' => 'Asia/Dushanbe'],
            473 => ['country' => 'Yemen', 'code' => 'YE', 'continent' => 'Asia', 'tz' => 'Asia/Aden'],
            475 => ['country' => 'Yemen', 'code' => 'YE', 'continent' => 'Asia', 'tz' => 'Asia/Aden'],
            477 => ['country' => 'Hong Kong', 'code' => 'HK', 'continent' => 'Asia', 'tz' => 'Asia/Hong_Kong'],
            478 => ['country' => 'Bosnia and Herzegovina', 'code' => 'BA', 'continent' => 'Europe', 'tz' => 'Europe/Sarajevo'],

            // Oceania & Southeast Asia
            501 => ['country' => 'Adelie Land', 'code' => 'AQ', 'continent' => 'Antarctica', 'tz' => 'Antarctica/DumontDUrville'],
            503 => ['country' => 'Australia', 'code' => 'AU', 'continent' => 'Oceania', 'tz' => 'Australia/Sydney'],
            506 => ['country' => 'Myanmar', 'code' => 'MM', 'continent' => 'Asia', 'tz' => 'Asia/Yangon'],
            508 => ['country' => 'Brunei', 'code' => 'BN', 'continent' => 'Asia', 'tz' => 'Asia/Brunei'],
            510 => ['country' => 'Micronesia', 'code' => 'FM', 'continent' => 'Oceania', 'tz' => 'Pacific/Pohnpei'],
            511 => ['country' => 'Palau', 'code' => 'PW', 'continent' => 'Oceania', 'tz' => 'Pacific/Palau'],
            512 => ['country' => 'New Zealand', 'code' => 'NZ', 'continent' => 'Oceania', 'tz' => 'Pacific/Auckland'],
            514 => ['country' => 'Cambodia', 'code' => 'KH', 'continent' => 'Asia', 'tz' => 'Asia/Phnom_Penh'],
            515 => ['country' => 'Cambodia', 'code' => 'KH', 'continent' => 'Asia', 'tz' => 'Asia/Phnom_Penh'],
            516 => ['country' => 'Christmas Island', 'code' => 'CX', 'continent' => 'Oceania', 'tz' => 'Indian/Christmas'],
            518 => ['country' => 'Cook Islands', 'code' => 'CK', 'continent' => 'Oceania', 'tz' => 'Pacific/Rarotonga'],
            520 => ['country' => 'Fiji', 'code' => 'FJ', 'continent' => 'Oceania', 'tz' => 'Pacific/Fiji'],
            523 => ['country' => 'Cocos (Keeling) Islands', 'code' => 'CC', 'continent' => 'Oceania', 'tz' => 'Indian/Cocos'],
            525 => ['country' => 'Indonesia', 'code' => 'ID', 'continent' => 'Asia', 'tz' => 'Asia/Jakarta'],
            529 => ['country' => 'Kiribati', 'code' => 'KI', 'continent' => 'Oceania', 'tz' => 'Pacific/Tarawa'],
            531 => ['country' => 'Laos', 'code' => 'LA', 'continent' => 'Asia', 'tz' => 'Asia/Vientiane'],
            533 => ['country' => 'Malaysia', 'code' => 'MY', 'continent' => 'Asia', 'tz' => 'Asia/Kuala_Lumpur'],
            536 => ['country' => 'Northern Mariana Islands', 'code' => 'MP', 'continent' => 'Oceania', 'tz' => 'Pacific/Saipan'],
            538 => ['country' => 'Marshall Islands', 'code' => 'MH', 'continent' => 'Oceania', 'tz' => 'Pacific/Majuro'],
            540 => ['country' => 'New Caledonia', 'code' => 'NC', 'continent' => 'Oceania', 'tz' => 'Pacific/Noumea'],
            542 => ['country' => 'Niue', 'code' => 'NU', 'continent' => 'Oceania', 'tz' => 'Pacific/Niue'],
            544 => ['country' => 'Nauru', 'code' => 'NR', 'continent' => 'Oceania', 'tz' => 'Pacific/Nauru'],
            546 => ['country' => 'French Polynesia', 'code' => 'PF', 'continent' => 'Oceania', 'tz' => 'Pacific/Tahiti'],
            548 => ['country' => 'Philippines', 'code' => 'PH', 'continent' => 'Asia', 'tz' => 'Asia/Manila'],
            553 => ['country' => 'Papua New Guinea', 'code' => 'PG', 'continent' => 'Oceania', 'tz' => 'Pacific/Port_Moresby'],
            555 => ['country' => 'Pitcairn Islands', 'code' => 'PN', 'continent' => 'Oceania', 'tz' => 'Pacific/Pitcairn'],
            557 => ['country' => 'Solomon Islands', 'code' => 'SB', 'continent' => 'Oceania', 'tz' => 'Pacific/Guadalcanal'],
            559 => ['country' => 'American Samoa', 'code' => 'AS', 'continent' => 'Oceania', 'tz' => 'Pacific/Pago_Pago'],
            561 => ['country' => 'Samoa', 'code' => 'WS', 'continent' => 'Oceania', 'tz' => 'Pacific/Apia'],
            563 => ['country' => 'Singapore', 'code' => 'SG', 'continent' => 'Asia', 'tz' => 'Asia/Singapore'],
            564 => ['country' => 'Singapore', 'code' => 'SG', 'continent' => 'Asia', 'tz' => 'Asia/Singapore'],
            565 => ['country' => 'Singapore', 'code' => 'SG', 'continent' => 'Asia', 'tz' => 'Asia/Singapore'],
            566 => ['country' => 'Singapore', 'code' => 'SG', 'continent' => 'Asia', 'tz' => 'Asia/Singapore'],
            567 => ['country' => 'Thailand', 'code' => 'TH', 'continent' => 'Asia', 'tz' => 'Asia/Bangkok'],
            570 => ['country' => 'Tonga', 'code' => 'TO', 'continent' => 'Oceania', 'tz' => 'Pacific/Tongatapu'],
            572 => ['country' => 'Tuvalu', 'code' => 'TV', 'continent' => 'Oceania', 'tz' => 'Pacific/Funafuti'],
            574 => ['country' => 'Vietnam', 'code' => 'VN', 'continent' => 'Asia', 'tz' => 'Asia/Ho_Chi_Minh'],
            576 => ['country' => 'Vanuatu', 'code' => 'VU', 'continent' => 'Oceania', 'tz' => 'Pacific/Efate'],
            577 => ['country' => 'Vanuatu', 'code' => 'VU', 'continent' => 'Oceania', 'tz' => 'Pacific/Efate'],
            578 => ['country' => 'Wallis and Futuna', 'code' => 'WF', 'continent' => 'Oceania', 'tz' => 'Pacific/Wallis'],

            // Africa
            601 => ['country' => 'South Africa', 'code' => 'ZA', 'continent' => 'Africa', 'tz' => 'Africa/Johannesburg'],
            603 => ['country' => 'Angola', 'code' => 'AO', 'continent' => 'Africa', 'tz' => 'Africa/Luanda'],
            605 => ['country' => 'Algeria', 'code' => 'DZ', 'continent' => 'Africa', 'tz' => 'Africa/Algiers'],
            607 => ['country' => 'Saint Paul and Amsterdam Islands', 'code' => 'TF', 'continent' => 'Africa', 'tz' => 'Indian/Kerguelen'],
            608 => ['country' => 'Ascension Island', 'code' => 'SH', 'continent' => 'Africa', 'tz' => 'Atlantic/St_Helena'],
            609 => ['country' => 'Burundi', 'code' => 'BI', 'continent' => 'Africa', 'tz' => 'Africa/Bujumbura'],
            610 => ['country' => 'Benin', 'code' => 'BJ', 'continent' => 'Africa', 'tz' => 'Africa/Porto-Novo'],
            611 => ['country' => 'Botswana', 'code' => 'BW', 'continent' => 'Africa', 'tz' => 'Africa/Gaborone'],
            612 => ['country' => 'Central African Republic', 'code' => 'CF', 'continent' => 'Africa', 'tz' => 'Africa/Bangui'],
            613 => ['country' => 'Cameroon', 'code' => 'CM', 'continent' => 'Africa', 'tz' => 'Africa/Douala'],
            615 => ['country' => 'Congo', 'code' => 'CG', 'continent' => 'Africa', 'tz' => 'Africa/Brazzaville'],
            616 => ['country' => 'Comoros', 'code' => 'KM', 'continent' => 'Africa', 'tz' => 'Indian/Comoro'],
            617 => ['country' => 'Cape Verde', 'code' => 'CV', 'continent' => 'Africa', 'tz' => 'Atlantic/Cape_Verde'],
            618 => ['country' => 'Crozet Archipelago', 'code' => 'TF', 'continent' => 'Africa', 'tz' => 'Indian/Kerguelen'],
            619 => ['country' => 'Ivory Coast', 'code' => 'CI', 'continent' => 'Africa', 'tz' => 'Africa/Abidjan'],
            620 => ['country' => 'Comoros', 'code' => 'KM', 'continent' => 'Africa', 'tz' => 'Indian/Comoro'],
            621 => ['country' => 'Djibouti', 'code' => 'DJ', 'continent' => 'Africa', 'tz' => 'Africa/Djibouti'],
            622 => ['country' => 'Egypt', 'code' => 'EG', 'continent' => 'Africa', 'tz' => 'Africa/Cairo'],
            624 => ['country' => 'Ethiopia', 'code' => 'ET', 'continent' => 'Africa', 'tz' => 'Africa/Addis_Ababa'],
            625 => ['country' => 'Eritrea', 'code' => 'ER', 'continent' => 'Africa', 'tz' => 'Africa/Asmara'],
            626 => ['country' => 'Gabon', 'code' => 'GA', 'continent' => 'Africa', 'tz' => 'Africa/Libreville'],
            627 => ['country' => 'Ghana', 'code' => 'GH', 'continent' => 'Africa', 'tz' => 'Africa/Accra'],
            629 => ['country' => 'Gambia', 'code' => 'GM', 'continent' => 'Africa', 'tz' => 'Africa/Banjul'],
            630 => ['country' => 'Guinea-Bissau', 'code' => 'GW', 'continent' => 'Africa', 'tz' => 'Africa/Bissau'],
            631 => ['country' => 'Equatorial Guinea', 'code' => 'GQ', 'continent' => 'Africa', 'tz' => 'Africa/Malabo'],
            632 => ['country' => 'Guinea', 'code' => 'GN', 'continent' => 'Africa', 'tz' => 'Africa/Conakry'],
            633 => ['country' => 'Burkina Faso', 'code' => 'BF', 'continent' => 'Africa', 'tz' => 'Africa/Ouagadougou'],
            634 => ['country' => 'Kenya', 'code' => 'KE', 'continent' => 'Africa', 'tz' => 'Africa/Nairobi'],
            635 => ['country' => 'Kerguelen Islands', 'code' => 'TF', 'continent' => 'Africa', 'tz' => 'Indian/Kerguelen'],
            636 => ['country' => 'Liberia', 'code' => 'LR', 'continent' => 'Africa', 'tz' => 'Africa/Monrovia'],
            637 => ['country' => 'Liberia', 'code' => 'LR', 'continent' => 'Africa', 'tz' => 'Africa/Monrovia'],
            638 => ['country' => 'South Sudan', 'code' => 'SS', 'continent' => 'Africa', 'tz' => 'Africa/Juba'],
            642 => ['country' => 'Libya', 'code' => 'LY', 'continent' => 'Africa', 'tz' => 'Africa/Tripoli'],
            644 => ['country' => 'Lesotho', 'code' => 'LS', 'continent' => 'Africa', 'tz' => 'Africa/Maseru'],
            645 => ['country' => 'Mauritius', 'code' => 'MU', 'continent' => 'Africa', 'tz' => 'Indian/Mauritius'],
            647 => ['country' => 'Madagascar', 'code' => 'MG', 'continent' => 'Africa', 'tz' => 'Indian/Antananarivo'],
            649 => ['country' => 'Mali', 'code' => 'ML', 'continent' => 'Africa', 'tz' => 'Africa/Bamako'],
            650 => ['country' => 'Mozambique', 'code' => 'MZ', 'continent' => 'Africa', 'tz' => 'Africa/Maputo'],
            654 => ['country' => 'Mauritania', 'code' => 'MR', 'continent' => 'Africa', 'tz' => 'Africa/Nouakchott'],
            655 => ['country' => 'Malawi', 'code' => 'MW', 'continent' => 'Africa', 'tz' => 'Africa/Blantyre'],
            656 => ['country' => 'Niger', 'code' => 'NE', 'continent' => 'Africa', 'tz' => 'Africa/Niamey'],
            657 => ['country' => 'Nigeria', 'code' => 'NG', 'continent' => 'Africa', 'tz' => 'Africa/Lagos'],
            659 => ['country' => 'Namibia', 'code' => 'NA', 'continent' => 'Africa', 'tz' => 'Africa/Windhoek'],
            660 => ['country' => 'Reunion', 'code' => 'RE', 'continent' => 'Africa', 'tz' => 'Indian/Reunion'],
            661 => ['country' => 'Rwanda', 'code' => 'RW', 'continent' => 'Africa', 'tz' => 'Africa/Kigali'],
            662 => ['country' => 'Sudan', 'code' => 'SD', 'continent' => 'Africa', 'tz' => 'Africa/Khartoum'],
            663 => ['country' => 'Senegal', 'code' => 'SN', 'continent' => 'Africa', 'tz' => 'Africa/Dakar'],
            664 => ['country' => 'Seychelles', 'code' => 'SC', 'continent' => 'Africa', 'tz' => 'Indian/Mahe'],
            665 => ['country' => 'Saint Helena', 'code' => 'SH', 'continent' => 'Africa', 'tz' => 'Atlantic/St_Helena'],
            666 => ['country' => 'Somalia', 'code' => 'SO', 'continent' => 'Africa', 'tz' => 'Africa/Mogadishu'],
            667 => ['country' => 'Sierra Leone', 'code' => 'SL', 'continent' => 'Africa', 'tz' => 'Africa/Freetown'],
            668 => ['country' => 'Sao Tome and Principe', 'code' => 'ST', 'continent' => 'Africa', 'tz' => 'Africa/Sao_Tome'],
            669 => ['country' => 'Eswatini', 'code' => 'SZ', 'continent' => 'Africa', 'tz' => 'Africa/Mbabane'],
            670 => ['country' => 'Chad', 'code' => 'TD', 'continent' => 'Africa', 'tz' => 'Africa/Ndjamena'],
            671 => ['country' => 'Togo', 'code' => 'TG', 'continent' => 'Africa', 'tz' => 'Africa/Lome'],
            672 => ['country' => 'Tunisia', 'code' => 'TN', 'continent' => 'Africa', 'tz' => 'Africa/Tunis'],
            674 => ['country' => 'Tanzania', 'code' => 'TZ', 'continent' => 'Africa', 'tz' => 'Africa/Dar_es_Salaam'],
            675 => ['country' => 'Uganda', 'code' => 'UG', 'continent' => 'Africa', 'tz' => 'Africa/Kampala'],
            676 => ['country' => 'DR Congo', 'code' => 'CD', 'continent' => 'Africa', 'tz' => 'Africa/Kinshasa'],
            677 => ['country' => 'Tanzania', 'code' => 'TZ', 'continent' => 'Africa', 'tz' => 'Africa/Dar_es_Salaam'],
            678 => ['country' => 'Zambia', 'code' => 'ZM', 'continent' => 'Africa', 'tz' => 'Africa/Lusaka'],
            679 => ['country' => 'Zimbabwe', 'code' => 'ZW', 'continent' => 'Africa', 'tz' => 'Africa/Harare'],

            // South America
            701 => ['country' => 'Argentina', 'code' => 'AR', 'continent' => 'South America', 'tz' => 'America/Argentina/Buenos_Aires'],
            710 => ['country' => 'Brazil', 'code' => 'BR', 'continent' => 'South America', 'tz' => 'America/Sao_Paulo'],
            720 => ['country' => 'Bolivia', 'code' => 'BO', 'continent' => 'South America', 'tz' => 'America/La_Paz'],
            725 => ['country' => 'Chile', 'code' => 'CL', 'continent' => 'South America', 'tz' => 'America/Santiago'],
            730 => ['country' => 'Colombia', 'code' => 'CO', 'continent' => 'South America', 'tz' => 'America/Bogota'],
            735 => ['country' => 'Ecuador', 'code' => 'EC', 'continent' => 'South America', 'tz' => 'America/Guayaquil'],
            740 => ['country' => 'Falkland Islands', 'code' => 'FK', 'continent' => 'South America', 'tz' => 'Atlantic/Stanley'],
            745 => ['country' => 'Guiana', 'code' => 'GF', 'continent' => 'South America', 'tz' => 'America/Cayenne'],
            750 => ['country' => 'Guyana', 'code' => 'GY', 'continent' => 'South America', 'tz' => 'America/Guyana'],
            755 => ['country' => 'Paraguay', 'code' => 'PY', 'continent' => 'South America', 'tz' => 'America/Asuncion'],
            760 => ['country' => 'Peru', 'code' => 'PE', 'continent' => 'South America', 'tz' => 'America/Lima'],
            765 => ['country' => 'Suriname', 'code' => 'SR', 'continent' => 'South America', 'tz' => 'America/Paramaribo'],
            770 => ['country' => 'Uruguay', 'code' => 'UY', 'continent' => 'South America', 'tz' => 'America/Montevideo'],
            775 => ['country' => 'Venezuela', 'code' => 'VE', 'continent' => 'South America', 'tz' => 'America/Caracas'],
        ];

        return $midMap[$mid] ?? [
            'country' => 'Unknown Registry ('.$mid.')',
            'code' => 'UN',
            'continent' => 'Unknown',
            'tz' => 'UTC',
        ];
    }

    /**
     * Resolve flag metadata from a 2-letter AIS/flag code.
     * This is a direct flag-code lookup and does not use MMSI registry data.
     */
    public static function getFlagDataByCode(?string $code): ?array
    {
        if (! $code) {
            return null;
        }

        $normalized = strtoupper($code);

        $map = [
            'XD' => ['country' => 'Adele Island', 'continent' => 'Oceania', 'tz' => 'Indian/Christmas'],
            'AF' => ['country' => 'Afghanistan', 'continent' => 'Asia', 'tz' => 'Asia/Kabul'],
            'AX' => ['country' => 'Aland Islands', 'continent' => 'Europe', 'tz' => 'Europe/Helsinki'],
            'XC' => ['country' => 'Alaska', 'continent' => 'North America', 'tz' => 'America/Anchorage'],
            'AL' => ['country' => 'Albania', 'continent' => 'Europe', 'tz' => 'Europe/Tirane'],
            'DZ' => ['country' => 'Algeria', 'continent' => 'Africa', 'tz' => 'Africa/Algiers'],
            'AS' => ['country' => 'American Samoa', 'continent' => 'Oceania', 'tz' => 'Pacific/Pago_Pago'],
            'AD' => ['country' => 'Andorra', 'continent' => 'Europe', 'tz' => 'Europe/Andorra'],
            'AO' => ['country' => 'Angola', 'continent' => 'Africa', 'tz' => 'Africa/Luanda'],
            'AI' => ['country' => 'Anguilla', 'continent' => 'North America', 'tz' => 'America/Anguilla'],
            'AQ' => ['country' => 'Antarctica', 'continent' => 'Antarctica', 'tz' => 'Antarctica/Casey'],
            'AG' => ['country' => 'Antigua and Barbuda', 'continent' => 'North America', 'tz' => 'America/Antigua'],
            'AR' => ['country' => 'Argentina', 'continent' => 'South America', 'tz' => 'America/Argentina/Buenos_Aires'],
            'AM' => ['country' => 'Armenia', 'continent' => 'Asia', 'tz' => 'Asia/Yerevan'],
            'AW' => ['country' => 'Aruba', 'continent' => 'North America', 'tz' => 'America/Aruba'],
            'XE' => ['country' => 'Ascension Island', 'continent' => 'Africa', 'tz' => 'Atlantic/St_Helena'],
            'AU' => ['country' => 'Australia', 'continent' => 'Oceania', 'tz' => 'Australia/Sydney'],
            'AT' => ['country' => 'Austria', 'continent' => 'Europe', 'tz' => 'Europe/Vienna'],
            'AZ' => ['country' => 'Azerbaijan', 'continent' => 'Asia', 'tz' => 'Asia/Baku'],
            'XA' => ['country' => 'Azores', 'continent' => 'Europe', 'tz' => 'Atlantic/Azores'],
            'BS' => ['country' => 'Bahamas', 'continent' => 'North America', 'tz' => 'America/Nassau'],
            'BH' => ['country' => 'Bahrain', 'continent' => 'Asia', 'tz' => 'Asia/Bahrain'],
            'BD' => ['country' => 'Bangladesh', 'continent' => 'Asia', 'tz' => 'Asia/Dhaka'],
            'BB' => ['country' => 'Barbados', 'continent' => 'North America', 'tz' => 'America/Barbados'],
            'BY' => ['country' => 'Belarus', 'continent' => 'Europe', 'tz' => 'Europe/Minsk'],
            'BE' => ['country' => 'Belgium', 'continent' => 'Europe', 'tz' => 'Europe/Brussels'],
            'BZ' => ['country' => 'Belize', 'continent' => 'North America', 'tz' => 'America/Belize'],
            'BJ' => ['country' => 'Benin', 'continent' => 'Africa', 'tz' => 'Africa/Porto-Novo'],
            'BM' => ['country' => 'Bermuda', 'continent' => 'North America', 'tz' => 'Atlantic/Bermuda'],
            'BT' => ['country' => 'Bhutan', 'continent' => 'Asia', 'tz' => 'Asia/Thimphu'],
            'BO' => ['country' => 'Bolivia', 'continent' => 'South America', 'tz' => 'America/La_Paz'],
            'BQ' => ['country' => 'Bonaire, Sint Eustatius and Saba', 'continent' => 'North America', 'tz' => 'America/Kralendijk'],
            'BA' => ['country' => 'Bosnia and Herzegovina', 'continent' => 'Europe', 'tz' => 'Europe/Sarajevo'],
            'BW' => ['country' => 'Botswana', 'continent' => 'Africa', 'tz' => 'Africa/Gaborone'],
            'BV' => ['country' => 'Bouvet Island', 'continent' => 'Antarctica', 'tz' => 'UTC'],
            'BR' => ['country' => 'Brazil', 'continent' => 'South America', 'tz' => 'America/Sao_Paulo'],
            'IO' => ['country' => 'British Indian Ocean Territory', 'continent' => 'Asia', 'tz' => 'Indian/Chagos'],
            'BN' => ['country' => 'Brunei Darussalam', 'continent' => 'Asia', 'tz' => 'Asia/Brunei'],
            'BG' => ['country' => 'Bulgaria', 'continent' => 'Europe', 'tz' => 'Europe/Sofia'],
            'BF' => ['country' => 'Burkina Faso', 'continent' => 'Africa', 'tz' => 'Africa/Ouagadougou'],
            'BI' => ['country' => 'Burundi', 'continent' => 'Africa', 'tz' => 'Africa/Bujumbura'],
            'CV' => ['country' => 'Cabo Verde', 'continent' => 'Africa', 'tz' => 'Atlantic/Cape_Verde'],
            'KH' => ['country' => 'Cambodia', 'continent' => 'Asia', 'tz' => 'Asia/Phnom_Penh'],
            'CM' => ['country' => 'Cameroon', 'continent' => 'Africa', 'tz' => 'Africa/Douala'],
            'CA' => ['country' => 'Canada', 'continent' => 'North America', 'tz' => 'America/Toronto'],
            'KY' => ['country' => 'Cayman Islands', 'continent' => 'North America', 'tz' => 'America/Cayman'],
            'CF' => ['country' => 'Central African Republic', 'continent' => 'Africa', 'tz' => 'Africa/Bangui'],
            'TD' => ['country' => 'Chad', 'continent' => 'Africa', 'tz' => 'Africa/Ndjamena'],
            'CL' => ['country' => 'Chile', 'continent' => 'South America', 'tz' => 'America/Santiago'],
            'CN' => ['country' => 'China', 'continent' => 'Asia', 'tz' => 'Asia/Shanghai'],
            'CX' => ['country' => 'Christmas Island', 'continent' => 'Oceania', 'tz' => 'Indian/Christmas'],
            'CC' => ['country' => 'Cocos (Keeling) Islands', 'continent' => 'Oceania', 'tz' => 'Indian/Cocos'],
            'CO' => ['country' => 'Colombia', 'continent' => 'South America', 'tz' => 'America/Bogota'],
            'KM' => ['country' => 'Comoros', 'continent' => 'Africa', 'tz' => 'Indian/Comoro'],
            'CG' => ['country' => 'Congo', 'continent' => 'Africa', 'tz' => 'Africa/Brazzaville'],
            'CD' => ['country' => 'Congo (DR)', 'continent' => 'Africa', 'tz' => 'Africa/Kinshasa'],
            'CK' => ['country' => 'Cook Islands', 'continent' => 'Oceania', 'tz' => 'Pacific/Rarotonga'],
            'CR' => ['country' => 'Costa Rica', 'continent' => 'North America', 'tz' => 'America/Costa_Rica'],
            'CI' => ['country' => "Cote d'Ivoire", 'continent' => 'Africa', 'tz' => 'Africa/Abidjan'],
            'HR' => ['country' => 'Croatia', 'continent' => 'Europe', 'tz' => 'Europe/Zagreb'],
            'XF' => ['country' => 'Crozet Archipelago', 'continent' => 'Antarctica', 'tz' => 'Indian/Kerguelen'],
            'CU' => ['country' => 'Cuba', 'continent' => 'North America', 'tz' => 'America/Havana'],
            'CW' => ['country' => 'Curacao', 'continent' => 'North America', 'tz' => 'America/Curacao'],
            'CY' => ['country' => 'Cyprus', 'continent' => 'Europe', 'tz' => 'Asia/Nicosia'],
            'CZ' => ['country' => 'Czech Republic', 'continent' => 'Europe', 'tz' => 'Europe/Prague'],
            'CS' => ['country' => 'Czechoslovakia', 'continent' => 'Europe', 'tz' => 'Europe/Prague'],
            'DK' => ['country' => 'Denmark', 'continent' => 'Europe', 'tz' => 'Europe/Copenhagen'],
            'DJ' => ['country' => 'Djibouti', 'continent' => 'Africa', 'tz' => 'Africa/Djibouti'],
            'DM' => ['country' => 'Dominica', 'continent' => 'North America', 'tz' => 'America/Dominica'],
            'DO' => ['country' => 'Dominican Republic', 'continent' => 'North America', 'tz' => 'America/Santo_Domingo'],
            'TL' => ['country' => 'East Timor', 'continent' => 'Asia', 'tz' => 'Asia/Dili'],
            'EC' => ['country' => 'Ecuador', 'continent' => 'South America', 'tz' => 'America/Guayaquil'],
            'EG' => ['country' => 'Egypt', 'continent' => 'Africa', 'tz' => 'Africa/Cairo'],
            'SV' => ['country' => 'El Salvador', 'continent' => 'North America', 'tz' => 'America/El_Salvador'],
            'GQ' => ['country' => 'Equatorial Guinea', 'continent' => 'Africa', 'tz' => 'Africa/Malabo'],
            'ER' => ['country' => 'Eritrea', 'continent' => 'Africa', 'tz' => 'Africa/Asmara'],
            'EE' => ['country' => 'Estonia', 'continent' => 'Europe', 'tz' => 'Europe/Tallinn'],
            'ET' => ['country' => 'Ethiopia', 'continent' => 'Africa', 'tz' => 'Africa/Addis_Ababa'],
            'FK' => ['country' => 'Falkland Islands', 'continent' => 'South America', 'tz' => 'Atlantic/Stanley'],
            'FO' => ['country' => 'Faroe Islands', 'continent' => 'Europe', 'tz' => 'Atlantic/Faroe'],
            'FJ' => ['country' => 'Fiji', 'continent' => 'Oceania', 'tz' => 'Pacific/Fiji'],
            'FI' => ['country' => 'Finland', 'continent' => 'Europe', 'tz' => 'Europe/Helsinki'],
            'FR' => ['country' => 'France', 'continent' => 'Europe', 'tz' => 'Europe/Paris'],
            'GF' => ['country' => 'French Guiana', 'continent' => 'South America', 'tz' => 'America/Cayenne'],
            'PF' => ['country' => 'French Polynesia', 'continent' => 'Oceania', 'tz' => 'Pacific/Tahiti'],
            'TF' => ['country' => 'French Southern Territories', 'continent' => 'Antarctica', 'tz' => 'Indian/Kerguelen'],
            'GA' => ['country' => 'Gabon', 'continent' => 'Africa', 'tz' => 'Africa/Libreville'],
            'GM' => ['country' => 'Gambia', 'continent' => 'Africa', 'tz' => 'Africa/Banjul'],
            'GE' => ['country' => 'Georgia', 'continent' => 'Europe', 'tz' => 'Asia/Tbilisi'],
            'DD' => ['country' => 'German Democratic Republic', 'continent' => 'Europe', 'tz' => 'Europe/Berlin'],
            'DE' => ['country' => 'Germany', 'continent' => 'Europe', 'tz' => 'Europe/Berlin'],
            'GH' => ['country' => 'Ghana', 'continent' => 'Africa', 'tz' => 'Africa/Accra'],
            'GI' => ['country' => 'Gibraltar', 'continent' => 'Europe', 'tz' => 'Europe/Gibraltar'],
            'GR' => ['country' => 'Greece', 'continent' => 'Europe', 'tz' => 'Europe/Athens'],
            'GL' => ['country' => 'Greenland', 'continent' => 'North America', 'tz' => 'America/Nuuk'],
            'GD' => ['country' => 'Grenada', 'continent' => 'North America', 'tz' => 'America/Grenada'],
            'GP' => ['country' => 'Guadeloupe', 'continent' => 'North America', 'tz' => 'America/Guadeloupe'],
            'GU' => ['country' => 'Guam', 'continent' => 'Oceania', 'tz' => 'Pacific/Guam'],
            'GT' => ['country' => 'Guatemala', 'continent' => 'North America', 'tz' => 'America/Guatemala'],
            'GG' => ['country' => 'Guernsey', 'continent' => 'Europe', 'tz' => 'Europe/Guernsey'],
            'GN' => ['country' => 'Guinea', 'continent' => 'Africa', 'tz' => 'Africa/Conakry'],
            'GW' => ['country' => 'Guinea-Bissau', 'continent' => 'Africa', 'tz' => 'Africa/Bissau'],
            'GY' => ['country' => 'Guyana', 'continent' => 'South America', 'tz' => 'America/Guyana'],
            'HT' => ['country' => 'Haiti', 'continent' => 'North America', 'tz' => 'America/Port-au-Prince'],
            'HM' => ['country' => 'Heard Island and McDonald Islands', 'continent' => 'Antarctica', 'tz' => 'Indian/Kerguelen'],
            'VA' => ['country' => 'Holy See', 'continent' => 'Europe', 'tz' => 'Europe/Vatican'],
            'HN' => ['country' => 'Honduras', 'continent' => 'North America', 'tz' => 'America/Tegucigalpa'],
            'HK' => ['country' => 'Hong Kong', 'continent' => 'Asia', 'tz' => 'Asia/Hong_Kong'],
            'HU' => ['country' => 'Hungary', 'continent' => 'Europe', 'tz' => 'Europe/Budapest'],
            'IS' => ['country' => 'Iceland', 'continent' => 'Europe', 'tz' => 'Atlantic/Reykjavik'],
            'IN' => ['country' => 'India', 'continent' => 'Asia', 'tz' => 'Asia/Kolkata'],
            'ID' => ['country' => 'Indonesia', 'continent' => 'Asia', 'tz' => 'Asia/Jakarta'],
            'IR' => ['country' => 'Iran', 'continent' => 'Asia', 'tz' => 'Asia/Tehran'],
            'IQ' => ['country' => 'Iraq', 'continent' => 'Asia', 'tz' => 'Asia/Baghdad'],
            'IE' => ['country' => 'Ireland', 'continent' => 'Europe', 'tz' => 'Europe/Dublin'],
            'IM' => ['country' => 'Isle of Man', 'continent' => 'Europe', 'tz' => 'Europe/Isle_of_Man'],
            'IL' => ['country' => 'Israel', 'continent' => 'Asia', 'tz' => 'Asia/Jerusalem'],
            'IT' => ['country' => 'Italy', 'continent' => 'Europe', 'tz' => 'Europe/Rome'],
            'JM' => ['country' => 'Jamaica', 'continent' => 'North America', 'tz' => 'America/Jamaica'],
            'JP' => ['country' => 'Japan', 'continent' => 'Asia', 'tz' => 'Asia/Tokyo'],
            'JE' => ['country' => 'Jersey', 'continent' => 'Europe', 'tz' => 'Europe/Jersey'],
            'JO' => ['country' => 'Jordan', 'continent' => 'Asia', 'tz' => 'Asia/Amman'],
            'KZ' => ['country' => 'Kazakhstan', 'continent' => 'Asia', 'tz' => 'Asia/Almaty'],
            'KE' => ['country' => 'Kenya', 'continent' => 'Africa', 'tz' => 'Africa/Nairobi'],
            'XG' => ['country' => 'Kerguelen Islands', 'continent' => 'Antarctica', 'tz' => 'Indian/Kerguelen'],
            'KI' => ['country' => 'Kiribati', 'continent' => 'Oceania', 'tz' => 'Pacific/Tarawa'],
            'KR' => ['country' => 'Korea', 'continent' => 'Asia', 'tz' => 'Asia/Seoul'],
            'KW' => ['country' => 'Kuwait', 'continent' => 'Asia', 'tz' => 'Asia/Kuwait'],
            'KG' => ['country' => 'Kyrgyzstan', 'continent' => 'Asia', 'tz' => 'Asia/Bishkek'],
            'LA' => ['country' => "Lao People's Democratic Republic", 'continent' => 'Asia', 'tz' => 'Asia/Vientiane'],
            'LV' => ['country' => 'Latvia', 'continent' => 'Europe', 'tz' => 'Europe/Riga'],
            'LB' => ['country' => 'Lebanon', 'continent' => 'Asia', 'tz' => 'Asia/Beirut'],
            'LS' => ['country' => 'Lesotho', 'continent' => 'Africa', 'tz' => 'Africa/Maseru'],
            'LR' => ['country' => 'Liberia', 'continent' => 'Africa', 'tz' => 'Africa/Monrovia'],
            'LY' => ['country' => 'Libya', 'continent' => 'Africa', 'tz' => 'Africa/Tripoli'],
            'LI' => ['country' => 'Liechtenstein', 'continent' => 'Europe', 'tz' => 'Europe/Vaduz'],
            'LT' => ['country' => 'Lithuania', 'continent' => 'Europe', 'tz' => 'Europe/Vilnius'],
            'LU' => ['country' => 'Luxembourg', 'continent' => 'Europe', 'tz' => 'Europe/Luxembourg'],
            'MO' => ['country' => 'Macao', 'continent' => 'Asia', 'tz' => 'Asia/Macau'],
            'MK' => ['country' => 'Macedonia (FYROM)', 'continent' => 'Europe', 'tz' => 'Europe/Skopje'],
            'MG' => ['country' => 'Madagascar', 'continent' => 'Africa', 'tz' => 'Indian/Antananarivo'],
            'XB' => ['country' => 'Madeira', 'continent' => 'Europe', 'tz' => 'Atlantic/Madeira'],
            'MW' => ['country' => 'Malawi', 'continent' => 'Africa', 'tz' => 'Africa/Blantyre'],
            'MY' => ['country' => 'Malaysia', 'continent' => 'Asia', 'tz' => 'Asia/Kuala_Lumpur'],
            'MV' => ['country' => 'Maldives', 'continent' => 'Asia', 'tz' => 'Indian/Maldives'],
            'ML' => ['country' => 'Mali', 'continent' => 'Africa', 'tz' => 'Africa/Bamako'],
            'MT' => ['country' => 'Malta', 'continent' => 'Europe', 'tz' => 'Europe/Malta'],
            'MH' => ['country' => 'Marshall Islands', 'continent' => 'Oceania', 'tz' => 'Pacific/Majuro'],
            'MQ' => ['country' => 'Martinique', 'continent' => 'North America', 'tz' => 'America/Martinique'],
            'MR' => ['country' => 'Mauritania', 'continent' => 'Africa', 'tz' => 'Africa/Nouakchott'],
            'MU' => ['country' => 'Mauritius', 'continent' => 'Africa', 'tz' => 'Indian/Mauritius'],
            'YT' => ['country' => 'Mayotte', 'continent' => 'Africa', 'tz' => 'Indian/Mayotte'],
            'MX' => ['country' => 'Mexico', 'continent' => 'North America', 'tz' => 'America/Mexico_City'],
            'FM' => ['country' => 'Micronesia', 'continent' => 'Oceania', 'tz' => 'Pacific/Pohnpei'],
            'MD' => ['country' => 'Moldova', 'continent' => 'Europe', 'tz' => 'Europe/Chisinau'],
            'MC' => ['country' => 'Monaco', 'continent' => 'Europe', 'tz' => 'Europe/Monaco'],
            'MN' => ['country' => 'Mongolia', 'continent' => 'Asia', 'tz' => 'Asia/Ulaanbaatar'],
            'ME' => ['country' => 'Montenegro', 'continent' => 'Europe', 'tz' => 'Europe/Podgorica'],
            'MS' => ['country' => 'Montserrat', 'continent' => 'North America', 'tz' => 'America/Montserrat'],
            'MA' => ['country' => 'Morocco', 'continent' => 'Africa', 'tz' => 'Africa/Casablanca'],
            'MZ' => ['country' => 'Mozambique', 'continent' => 'Africa', 'tz' => 'Africa/Maputo'],
            'MM' => ['country' => 'Myanmar', 'continent' => 'Asia', 'tz' => 'Asia/Yangon'],
            'NA' => ['country' => 'Namibia', 'continent' => 'Africa', 'tz' => 'Africa/Windhoek'],
            'NR' => ['country' => 'Nauru', 'continent' => 'Oceania', 'tz' => 'Pacific/Nauru'],
            'NP' => ['country' => 'Nepal', 'continent' => 'Asia', 'tz' => 'Asia/Kathmandu'],
            'NL' => ['country' => 'Netherlands', 'continent' => 'Europe', 'tz' => 'Europe/Amsterdam'],
            'AN' => ['country' => 'Netherlands Antilles', 'continent' => 'North America', 'tz' => 'America/Curacao'],
            'NC' => ['country' => 'New Caledonia', 'continent' => 'Oceania', 'tz' => 'Pacific/Noumea'],
            'NZ' => ['country' => 'New Zealand', 'continent' => 'Oceania', 'tz' => 'Pacific/Auckland'],
            'NI' => ['country' => 'Nicaragua', 'continent' => 'North America', 'tz' => 'America/Managua'],
            'NE' => ['country' => 'Niger', 'continent' => 'Africa', 'tz' => 'Africa/Niamey'],
            'NG' => ['country' => 'Nigeria', 'continent' => 'Africa', 'tz' => 'Africa/Lagos'],
            'NU' => ['country' => 'Niue', 'continent' => 'Oceania', 'tz' => 'Pacific/Niue'],
            'NF' => ['country' => 'Norfolk Island', 'continent' => 'Oceania', 'tz' => 'Pacific/Norfolk'],
            'KP' => ['country' => 'North Korea', 'continent' => 'Asia', 'tz' => 'Asia/Pyongyang'],
            'MP' => ['country' => 'Northern Mariana Islands', 'continent' => 'Oceania', 'tz' => 'Pacific/Saipan'],
            'NO' => ['country' => 'Norway', 'continent' => 'Europe', 'tz' => 'Europe/Oslo'],
            'OM' => ['country' => 'Oman', 'continent' => 'Asia', 'tz' => 'Asia/Muscat'],
            'PK' => ['country' => 'Pakistan', 'continent' => 'Asia', 'tz' => 'Asia/Karachi'],
            'PW' => ['country' => 'Palau', 'continent' => 'Oceania', 'tz' => 'Pacific/Palau'],
            'PS' => ['country' => 'Palestine', 'continent' => 'Asia', 'tz' => 'Asia/Gaza'],
            'PA' => ['country' => 'Panama', 'continent' => 'North America', 'tz' => 'America/Panama'],
            'PG' => ['country' => 'Papua New Guinea', 'continent' => 'Oceania', 'tz' => 'Pacific/Port_Moresby'],
            'PY' => ['country' => 'Paraguay', 'continent' => 'South America', 'tz' => 'America/Asuncion'],
            'PE' => ['country' => 'Peru', 'continent' => 'South America', 'tz' => 'America/Lima'],
            'PH' => ['country' => 'Philippines', 'continent' => 'Asia', 'tz' => 'Asia/Manila'],
            'PN' => ['country' => 'Pitcairn', 'continent' => 'Oceania', 'tz' => 'Pacific/Pitcairn'],
            'PL' => ['country' => 'Poland', 'continent' => 'Europe', 'tz' => 'Europe/Warsaw'],
            'PT' => ['country' => 'Portugal', 'continent' => 'Europe', 'tz' => 'Europe/Lisbon'],
            'PR' => ['country' => 'Puerto Rico', 'continent' => 'North America', 'tz' => 'America/Puerto_Rico'],
            'QA' => ['country' => 'Qatar', 'continent' => 'Asia', 'tz' => 'Asia/Qatar'],
            'RE' => ['country' => 'Reunion', 'continent' => 'Africa', 'tz' => 'Indian/Reunion'],
            'RO' => ['country' => 'Romania', 'continent' => 'Europe', 'tz' => 'Europe/Bucharest'],
            'RU' => ['country' => 'Russian Federation', 'continent' => 'Europe', 'tz' => 'Europe/Moscow'],
            'RW' => ['country' => 'Rwanda', 'continent' => 'Africa', 'tz' => 'Africa/Kigali'],
            'BL' => ['country' => 'Saint Barthelemy', 'continent' => 'North America', 'tz' => 'America/St_Barthelemy'],
            'SH' => ['country' => 'Saint Helena, Ascension and Tristan da Cunha', 'continent' => 'Africa', 'tz' => 'Atlantic/St_Helena'],
            'KN' => ['country' => 'Saint Kitts and Nevis', 'continent' => 'North America', 'tz' => 'America/St_Kitts'],
            'LC' => ['country' => 'Saint Lucia', 'continent' => 'North America', 'tz' => 'America/St_Lucia'],
            'MF' => ['country' => 'Saint Martin (FR)', 'continent' => 'North America', 'tz' => 'America/Marigot'],
            'XI' => ['country' => 'Saint Paul and Amsterdam Islands', 'continent' => 'Antarctica', 'tz' => 'Indian/Kerguelen'],
            'PM' => ['country' => 'Saint Pierre and Miquelon', 'continent' => 'North America', 'tz' => 'America/Miquelon'],
            'VC' => ['country' => 'Saint Vincent and the Grenadines', 'continent' => 'North America', 'tz' => 'America/St_Vincent'],
            'WS' => ['country' => 'Samoa', 'continent' => 'Oceania', 'tz' => 'Pacific/Apia'],
            'SM' => ['country' => 'San Marino', 'continent' => 'Europe', 'tz' => 'Europe/San_Marino'],
            'ST' => ['country' => 'Sao Tome and Principe', 'continent' => 'Africa', 'tz' => 'Africa/Sao_Tome'],
            'SA' => ['country' => 'Saudi Arabia', 'continent' => 'Asia', 'tz' => 'Asia/Riyadh'],
            'SN' => ['country' => 'Senegal', 'continent' => 'Africa', 'tz' => 'Africa/Dakar'],
            'RS' => ['country' => 'Serbia', 'continent' => 'Europe', 'tz' => 'Europe/Belgrade'],
            'SC' => ['country' => 'Seychelles', 'continent' => 'Africa', 'tz' => 'Indian/Mahe'],
            'SL' => ['country' => 'Sierra Leone', 'continent' => 'Africa', 'tz' => 'Africa/Freetown'],
            'SG' => ['country' => 'Singapore', 'continent' => 'Asia', 'tz' => 'Asia/Singapore'],
            'SX' => ['country' => 'Sint Maarten (NL)', 'continent' => 'North America', 'tz' => 'America/Lower_Princes'],
            'SK' => ['country' => 'Slovakia', 'continent' => 'Europe', 'tz' => 'Europe/Bratislava'],
            'SI' => ['country' => 'Slovenia', 'continent' => 'Europe', 'tz' => 'Europe/Ljubljana'],
            'SB' => ['country' => 'Solomon Islands', 'continent' => 'Oceania', 'tz' => 'Pacific/Guadalcanal'],
            'SO' => ['country' => 'Somalia', 'continent' => 'Africa', 'tz' => 'Africa/Mogadishu'],
            'ZA' => ['country' => 'South Africa', 'continent' => 'Africa', 'tz' => 'Africa/Johannesburg'],
            'GS' => ['country' => 'South Georgia and the South Sandwich Islands', 'continent' => 'Antarctica', 'tz' => 'Atlantic/South_Georgia'],
            'SS' => ['country' => 'South Sudan', 'continent' => 'Africa', 'tz' => 'Africa/Juba'],
            'ES' => ['country' => 'Spain', 'continent' => 'Europe', 'tz' => 'Europe/Madrid'],
            'LK' => ['country' => 'Sri Lanka', 'continent' => 'Asia', 'tz' => 'Asia/Colombo'],
            'SD' => ['country' => 'Sudan', 'continent' => 'Africa', 'tz' => 'Africa/Khartoum'],
            'SR' => ['country' => 'Suriname', 'continent' => 'South America', 'tz' => 'America/Paramaribo'],
            'SJ' => ['country' => 'Svalbard and Jan Mayen', 'continent' => 'Europe', 'tz' => 'Arctic/Longyearbyen'],
            'SZ' => ['country' => 'Swaziland', 'continent' => 'Africa', 'tz' => 'Africa/Mbabane'],
            'SE' => ['country' => 'Sweden', 'continent' => 'Europe', 'tz' => 'Europe/Stockholm'],
            'CH' => ['country' => 'Switzerland', 'continent' => 'Europe', 'tz' => 'Europe/Zurich'],
            'SY' => ['country' => 'Syrian Arab Republic', 'continent' => 'Asia', 'tz' => 'Asia/Damascus'],
            'XH' => ['country' => 'Tahiti', 'continent' => 'Oceania', 'tz' => 'Pacific/Tahiti'],
            'TW' => ['country' => 'Taiwan (Province of China)', 'continent' => 'Asia', 'tz' => 'Asia/Taipei'],
            'TJ' => ['country' => 'Tajikistan', 'continent' => 'Asia', 'tz' => 'Asia/Dushanbe'],
            'TZ' => ['country' => 'Tanzania', 'continent' => 'Africa', 'tz' => 'Africa/Dar_es_Salaam'],
            'TH' => ['country' => 'Thailand', 'continent' => 'Asia', 'tz' => 'Asia/Bangkok'],
            'TG' => ['country' => 'Togo', 'continent' => 'Africa', 'tz' => 'Africa/Lome'],
            'TK' => ['country' => 'Tokelau', 'continent' => 'Oceania', 'tz' => 'Pacific/Fakaofo'],
            'TO' => ['country' => 'Tonga', 'continent' => 'Oceania', 'tz' => 'Pacific/Tongatapu'],
            'TT' => ['country' => 'Trinidad and Tobago', 'continent' => 'North America', 'tz' => 'America/Port_of_Spain'],
            'TN' => ['country' => 'Tunisia', 'continent' => 'Africa', 'tz' => 'Africa/Tunis'],
            'TR' => ['country' => 'Turkey', 'continent' => 'Europe', 'tz' => 'Europe/Istanbul'],
            'TM' => ['country' => 'Turkmenistan', 'continent' => 'Asia', 'tz' => 'Asia/Ashgabat'],
            'TC' => ['country' => 'Turks and Caicos Islands', 'continent' => 'North America', 'tz' => 'America/Grand_Turk'],
            'TV' => ['country' => 'Tuvalu', 'continent' => 'Oceania', 'tz' => 'Pacific/Funafuti'],
            'UG' => ['country' => 'Uganda', 'continent' => 'Africa', 'tz' => 'Africa/Kampala'],
            'UA' => ['country' => 'Ukraine', 'continent' => 'Europe', 'tz' => 'Europe/Kyiv'],
            'AE' => ['country' => 'United Arab Emirates', 'continent' => 'Asia', 'tz' => 'Asia/Dubai'],
            'GB' => ['country' => 'United Kingdom', 'continent' => 'Europe', 'tz' => 'Europe/London'],
            'UM' => ['country' => 'United States Minor Outlying Islands', 'continent' => 'North America', 'tz' => 'Pacific/Honolulu'],
            'US' => ['country' => 'United States of America', 'continent' => 'North America', 'tz' => 'America/New_York'],
            'ZZ' => ['country' => 'Unknown', 'continent' => 'Unknown', 'tz' => 'UTC'],
            'UY' => ['country' => 'Uruguay', 'continent' => 'South America', 'tz' => 'America/Montevideo'],
            'UZ' => ['country' => 'Uzbekistan', 'continent' => 'Asia', 'tz' => 'Asia/Tashkent'],
            'VU' => ['country' => 'Vanuatu', 'continent' => 'Oceania', 'tz' => 'Pacific/Efate'],
            'VE' => ['country' => 'Venezuela', 'continent' => 'South America', 'tz' => 'America/Caracas'],
            'VN' => ['country' => 'Viet Nam', 'continent' => 'Asia', 'tz' => 'Asia/Ho_Chi_Minh'],
            'VG' => ['country' => 'Virgin Islands (GB)', 'continent' => 'North America', 'tz' => 'America/Tortola'],
            'VI' => ['country' => 'Virgin Islands (US)', 'continent' => 'North America', 'tz' => 'America/St_Thomas'],
            'WF' => ['country' => 'Wallis and Futuna', 'continent' => 'Oceania', 'tz' => 'Pacific/Wallis'],
            'EH' => ['country' => 'Western Sahara', 'continent' => 'Africa', 'tz' => 'Africa/El_Aaiun'],
            'YE' => ['country' => 'Yemen', 'continent' => 'Asia', 'tz' => 'Asia/Aden'],
            'YU' => ['country' => 'Yugoslavia', 'continent' => 'Europe', 'tz' => 'Europe/Belgrade'],
            'ZM' => ['country' => 'Zambia', 'continent' => 'Africa', 'tz' => 'Africa/Lusaka'],
            'ZW' => ['country' => 'Zimbabwe', 'continent' => 'Africa', 'tz' => 'Africa/Harare'],
        ];

        if (! isset($map[$normalized])) {
            return [
                'country' => 'Unknown',
                'continent' => 'Unknown',
                'tz' => 'UTC',
            ];
        }

        $location = $map[$normalized];

        return [
            'country' => $location['country'],
            'continent' => $location['continent'],
            'tz' => $location['tz'],
        ];
    }
}
